# Generated by Django 4.2.27 on 2026-01-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('favorito', 'Favorito actualizado'), ('contacto', 'Nueva solicitud de contacto'), ('suscripcion', 'Recordatorio de suscripción'), ('valoracion', 'Nueva valoración'), ('validacion', 'Validación completada'), ('sistema', 'Notificación del sistema')], max_length=20),
        ),
    ]
