# Generated by Django 5.2.9 on 2025-12-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('contactado', 'Contactado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud de contacto',
                'verbose_name_plural': 'Solicitudes de contacto',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
