# Generated by Django 5.2.9 on 2025-12-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcontacto',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
