# Generated by Django 4.2.27 on 2026-08-16 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_publicacioncompanero_precio_mensual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contactos', '0004_solicitudcontacto_fecha_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudContactoCompanero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('contactado', 'Contactado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_contacto', to='usuarios.publicacioncompanero')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_contacto_companero', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de contacto (compañero/a)',
                'verbose_name_plural': 'Solicitudes de contacto (compañero/a)',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
