# Generated by Django 4.2.27 on 2026-01-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='objetivo_principal',
            field=models.CharField(blank=True, choices=[('buscar_alquiler', 'Buscar un lugar para alquilar'), ('buscar_compra', 'Buscar un lugar para comprar'), ('publicar_propiedad', 'Publicar mi propiedad'), ('gestionar_propiedades', 'Gestionar varias propiedades'), ('solo_explorar', 'Solo estoy explorando')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('estudiante', 'Estudiante'), ('dueno_directo', 'Dueño Directo'), ('inmobiliaria', 'Inmobiliaria'), ('interesado', 'Interesado en Alquilar/Comprar')], max_length=20, null=True),
        ),
    ]
