# Generated by Django 4.2.27 on 2026-01-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_objetivo_principal_perfil_perfil_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono_validado',
            field=models.BooleanField(default=False),
        ),
    ]
