# Generated by Django 4.2.27 on 2026-01-06 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_email_validado_usuario_telefono_validado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacion_actual', models.CharField(choices=[('tengo_lugar', 'Ya tengo un lugar y busco compañero/a'), ('busco_compartir', 'No tengo lugar, busco con quién compartir')], max_length=20, verbose_name='Situación actual')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('prefiero_no_decir', 'Prefiero no decir')], max_length=20, verbose_name='Género')),
                ('situacion_laboral', models.CharField(choices=[('estudiante', 'Estudiante'), ('trabajador', 'Trabajador/a'), ('ambas', 'Estudiante y Trabajador/a'), ('otra', 'Otra')], max_length=15, verbose_name='Situación laboral/académica')),
                ('universidad', models.CharField(blank=True, max_length=200, verbose_name='Universidad')),
                ('modalidad_estudio', models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hibrida', 'Híbrida')], max_length=15, verbose_name='Modalidad de estudio')),
                ('empresa_rubro', models.CharField(blank=True, max_length=200, verbose_name='Empresa o rubro')),
                ('modalidad_trabajo', models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], max_length=15, verbose_name='Modalidad de trabajo')),
                ('presupuesto_maximo', models.CharField(choices=[('0-50000', 'Hasta $50.000'), ('50000-100000', '$50.000 - $100.000'), ('100000-150000', '$100.000 - $150.000'), ('150000-200000', '$150.000 - $200.000'), ('200000-300000', '$200.000 - $300.000'), ('300000+', 'Más de $300.000')], max_length=20, verbose_name='Presupuesto máximo mensual')),
                ('zona_preferida', models.CharField(max_length=200, verbose_name='Zona preferida')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha aproximada de ingreso')),
                ('duracion_minima', models.CharField(choices=[('3_meses', '3 meses'), ('6_meses', '6 meses'), ('1_año', '1 año'), ('2_años', '2 años'), ('indefinido', 'Indefinido')], max_length=15, verbose_name='Duración mínima deseada')),
                ('fumador', models.BooleanField(default=False, verbose_name='¿Fumas?')),
                ('mascotas', models.BooleanField(default=False, verbose_name='¿Tienes mascotas?')),
                ('preferencia_convivencia', models.CharField(choices=[('tranquila', 'Tranquila (poco contacto social)'), ('equilibrada', 'Equilibrada'), ('social', 'Social (mucha interacción)')], max_length=15, verbose_name='Preferencia de convivencia')),
                ('horario_descanso', models.CharField(choices=[('temprano', 'Temprano (antes de las 22:00)'), ('normal', 'Normal (22:00 - 00:00)'), ('tarde', 'Tarde (después de las 00:00)')], max_length=15, verbose_name='Horario de descanso')),
                ('orden_limpieza', models.CharField(choices=[('basico', 'Básico'), ('prolijo', 'Prolijo'), ('muy_prolijo', 'Muy prolijo'), ('indistinto', 'Me es indistinto')], max_length=15, verbose_name='Orden y limpieza')),
                ('visitas', models.CharField(choices=[('ocasionales', 'Ocasionales'), ('frecuentes', 'Frecuentes'), ('no_molesta', 'No me molesta'), ('no_me_gustan', 'Prefiero sin visitas')], max_length=15, verbose_name='Visitas')),
                ('uso_espacios_comunes', models.CharField(choices=[('compartidos', 'Compartir los espacios comunes'), ('horarios', 'Usar en horarios distintos'), ('indistinto', 'Me es indistinto')], max_length=15, verbose_name='Uso de espacios comunes')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_busqueda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Búsqueda',
                'verbose_name_plural': 'Perfiles de Búsqueda',
            },
        ),
    ]
