# Generated by Django 4.2.27 on 2026-01-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfilbusqueda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilbusqueda',
            name='duracion_minima',
        ),
        migrations.RemoveField(
            model_name='perfilbusqueda',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='perfilbusqueda',
            name='fumador',
        ),
        migrations.RemoveField(
            model_name='perfilbusqueda',
            name='horario_descanso',
        ),
        migrations.RemoveField(
            model_name='perfilbusqueda',
            name='mascotas',
        ),
        migrations.RemoveField(
            model_name='perfilbusqueda',
            name='orden_limpieza',
        ),
        migrations.RemoveField(
            model_name='perfilbusqueda',
            name='preferencia_convivencia',
        ),
        migrations.RemoveField(
            model_name='perfilbusqueda',
            name='presupuesto_maximo',
        ),
        migrations.RemoveField(
            model_name='perfilbusqueda',
            name='uso_espacios_comunes',
        ),
        migrations.RemoveField(
            model_name='perfilbusqueda',
            name='visitas',
        ),
        migrations.RemoveField(
            model_name='perfilbusqueda',
            name='zona_preferida',
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='comida_social',
            field=models.JSONField(blank=True, default=list, verbose_name='Comida y Social'),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='convivencia_limpieza',
            field=models.JSONField(blank=True, default=list, verbose_name='Convivencia y Limpieza'),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='habitos_vicios',
            field=models.JSONField(blank=True, default=list, verbose_name='Hábitos y Vicios'),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='horarios_trabajo',
            field=models.JSONField(blank=True, default=list, verbose_name='Horarios y Trabajo'),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='mascotas_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Mascotas'),
        ),
    ]
