# Generated by Django 4.2.27 on 2026-01-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_perfilbusqueda_duracion_minima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='comida_social',
            field=models.JSONField(blank=True, default=list, verbose_name='Comida y Social'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='convivencia_limpieza',
            field=models.JSONField(blank=True, default=list, verbose_name='Convivencia y Limpieza'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='empresa_rubro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Empresa o rubro'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('prefiero_no_decir', 'Prefiero no decir')], max_length=20, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='habitos_vicios',
            field=models.JSONField(blank=True, default=list, verbose_name='Hábitos y Vicios'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='horarios_trabajo',
            field=models.JSONField(blank=True, default=list, verbose_name='Horarios y Trabajo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='mascotas_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Mascotas'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='modalidad_estudio',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hibrida', 'Híbrida')], max_length=15, verbose_name='Modalidad de estudio'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='modalidad_trabajo',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], max_length=15, verbose_name='Modalidad de trabajo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='situacion_actual',
            field=models.CharField(blank=True, choices=[('tengo_lugar', 'Ya tengo un lugar y busco compañero/a'), ('busco_compartir', 'No tengo lugar, busco con quién compartir')], max_length=20, null=True, verbose_name='Situación actual'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='situacion_laboral',
            field=models.CharField(blank=True, choices=[('estudiante', 'Estudiante'), ('trabajador', 'Trabajador/a'), ('ambas', 'Estudiante y Trabajador/a'), ('otra', 'Otra')], max_length=15, null=True, verbose_name='Situación laboral/académica'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='universidad',
            field=models.CharField(blank=True, max_length=200, verbose_name='Universidad'),
        ),
    ]
