# Generated by Django 4.2.27 on 2026-03-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_perfil_comida_social_perfil_convivencia_limpieza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='presentacion',
            field=models.TextField(blank=True, help_text='Contá un poco sobre vos y qué buscás en un compañero/a de vivienda (máx. 500 caracteres)', max_length=500, verbose_name='Presentación personal'),
        ),
    ]
