# Generated by Django 4.2.27 on 2026-03-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_perfil_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='icono_avatar',
            field=models.CharField(blank=True, help_text='Emoji o código del icono', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_avatar',
            field=models.CharField(choices=[('foto', 'Foto'), ('icono', 'Icono')], default='foto', max_length=10),
        ),
    ]
