# Generated by Django 4.2.27 on 2026-03-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usuario_icono_avatar_usuario_tipo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='biografia',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
