# Generated by Django 4.2.27 on 2026-03-16 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_usuario_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='biografia',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='PublicacionCompanero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Busco compañero/a para compartir depto 2 ambientes en Palermo', max_length=200, verbose_name='Título de la publicación')),
                ('descripcion', models.TextField(help_text='Contá más sobre el departamento y qué buscás en un compañero/a', verbose_name='Descripción')),
                ('provincia', models.CharField(default='Buenos Aires', max_length=100)),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('distrito', models.CharField(max_length=100, verbose_name='Barrio/Distrito')),
                ('direccion', models.CharField(help_text='No es necesario dar la dirección exacta por seguridad', max_length=255, verbose_name='Dirección aproximada')),
                ('habitaciones_totales', models.IntegerField(default=1, help_text='Habitaciones totales del departamento', verbose_name='Habitaciones totales')),
                ('habitaciones_disponibles', models.IntegerField(default=1, help_text='Habitaciones disponibles para el/la compañero/a', verbose_name='Habitaciones disponibles')),
                ('banos', models.IntegerField(default=1, verbose_name='Baños')),
                ('amoblado', models.BooleanField(default=False, verbose_name='Habitación amoblada')),
                ('balcon', models.BooleanField(default=False, verbose_name='Tiene balcón o terraza')),
                ('cocina', models.BooleanField(default=True, verbose_name='Cocina equipada')),
                ('wifi', models.BooleanField(default=True, verbose_name='WiFi')),
                ('lavarropas', models.BooleanField(default=False, verbose_name='Lavarropas')),
                ('aire_acondicionado', models.BooleanField(default=False, verbose_name='Aire acondicionado')),
                ('calefaccion', models.BooleanField(default=False, verbose_name='Calefacción')),
                ('precio_mensual', models.DecimalField(decimal_places=2, help_text='Precio que pagaría cada persona por mes', max_digits=10, verbose_name='Precio mensual por persona')),
                ('expensas_incluidas', models.BooleanField(default=False, verbose_name='Expensas incluidas en el precio')),
                ('servicios_incluidos', models.BooleanField(default=False, help_text='Luz, gas, agua, internet', verbose_name='Servicios incluidos')),
                ('preferencia_genero', models.CharField(choices=[('indiferente', 'Indiferente'), ('masculino', 'Preferentemente masculino'), ('femenino', 'Preferentemente femenino')], default='indiferente', max_length=20, verbose_name='Preferencia de género')),
                ('acepta_mascotas', models.BooleanField(default=False, verbose_name='Acepta mascotas')),
                ('fumador_acepto', models.BooleanField(default=False, verbose_name='Acepta fumadores')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('completada', 'Completada - Ya encontré compañero/a'), ('inactiva', 'Inactiva')], default='activa', max_length=20, verbose_name='Estado de la publicación')),
                ('fecha_disponibilidad', models.DateField(blank=True, help_text='¿Desde cuándo está disponible?', null=True, verbose_name='Fecha de disponibilidad')),
                ('vistas', models.IntegerField(default=0, verbose_name='Vistas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(help_text='Usuario que tiene lugar y busca compañero/a', on_delete=django.db.models.deletion.CASCADE, related_name='publicacion_companero', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicación de Compañero/a',
                'verbose_name_plural': 'Publicaciones de Compañero/a',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenPublicacionCompanero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='publicaciones_companero/', verbose_name='Imagen')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='usuarios.publicacioncompanero')),
            ],
            options={
                'verbose_name': 'Imagen de Publicación',
                'verbose_name_plural': 'Imágenes de Publicación',
                'ordering': ['orden', 'fecha_subida'],
            },
        ),
    ]
