# Generated by Django 4.2.27 on 2026-03-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_usuario_biografia_publicacioncompanero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacioncompanero',
            name='precio_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio que pagaría cada persona por mes', max_digits=10, null=True, verbose_name='Precio mensual por persona'),
        ),
    ]
