# Generated by Django 4.2.27 on 2026-03-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_publicacioncompanero_precio_mensual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacioncompanero',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=2, default=50000, help_text='Precio que pagaría cada persona por mes', max_digits=10, verbose_name='Precio mensual por persona'),
            preserve_default=False,
        ),
    ]
