# Generated by Django 4.2.27 on 2026-08-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_publicacioncompanero_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacioncompanero',
            name='moneda',
            field=models.CharField(choices=[('ARS', '$ ARS'), ('USD', 'US$ USD')], default='ARS', max_length=3),
        ),
    ]
