# Generated by Django 4.2.27 on 2025-12-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansuscripcion',
            name='destacados_incluidos_mes',
            field=models.IntegerField(default=0, help_text='Número de destacados incluidos por mes'),
        ),
        migrations.AddField(
            model_name='plansuscripcion',
            name='puede_comprar_destacados',
            field=models.BooleanField(default=False, help_text='¿Puede comprar destacados adicionales?'),
        ),
    ]
