# Generated by Django 5.2.9 on 2025-12-27 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades', to='propiedades.categoria'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagenpropiedad',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='propiedades.propiedad'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='propiedades.propiedad'),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='propiedades.propiedad'),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'propiedad')},
        ),
        migrations.AlterUniqueTogether(
            name='valoracion',
            unique_together={('usuario', 'propiedad')},
        ),
    ]
