# Generated by Django 5.2.9 on 2025-12-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='especial_estudiantes',
            field=models.BooleanField(default=False, help_text='Propiedad especial para estudiantes'),
        ),
    ]
