# Generated by Django 5.2.9 on 2025-12-28 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_propiedad_especial_estudiantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='operacion',
            field=models.CharField(choices=[('alquiler', 'Alquiler'), ('venta', 'Venta')], default='alquiler', max_length=20),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades', to='propiedades.categoria'),
        ),
    ]
