# Generated by Django 5.2.9 on 2025-12-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0004_propiedad_operacion_alter_propiedad_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='incluye_expensas',
            field=models.BooleanField(default=False, help_text='¿El precio incluye gastos de expensas?'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_contacto',
            field=models.CharField(choices=[('dueno', 'Dueño Directo'), ('inmobiliaria', 'Inmobiliaria')], default='dueno', max_length=20),
        ),
    ]
