# Generated by Django 5.2.9 on 2025-12-29 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_propiedad_incluye_expensas_propiedad_tipo_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracion',
            name='puntuacion',
        ),
        migrations.AddField(
            model_name='valoracion',
            name='claridad_informacion',
            field=models.IntegerField(default=3, help_text='Claridad de la información', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='coincidencia_fotos',
            field=models.IntegerField(default=3, help_text='Coincidencia fotos/realidad', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='confiabilidad',
            field=models.IntegerField(default=3, help_text='Confiabilidad', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='tiempo_respuesta',
            field=models.IntegerField(default=3, help_text='Tiempo de respuesta', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='trato',
            field=models.IntegerField(default=3, help_text='Trato y predisposición', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='ubicacion_correcta',
            field=models.IntegerField(default=3, help_text='Ubicación correcta', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
