# Generated by Django 5.2.9 on 2025-12-29 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0006_remove_valoracion_puntuacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='fecha_ultima_edicion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='reportada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='total_reportes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ReporteValoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('falsa', 'Información falsa'), ('ofensiva', 'Contenido ofensivo'), ('spam', 'Spam o irrelevante'), ('venganza', 'Valoración vengativa'), ('otro', 'Otro motivo')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('revisado', models.BooleanField(default=False)),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_realizados', to=settings.AUTH_USER_MODEL)),
                ('valoracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='propiedades.valoracion')),
            ],
            options={
                'verbose_name': 'Reporte de Valoración',
                'verbose_name_plural': 'Reportes de Valoraciones',
                'ordering': ['-fecha_reporte'],
                'unique_together': {('valoracion', 'reportado_por')},
            },
        ),
    ]
