# Generated by Django 5.2.9 on 2025-12-29 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0007_valoracion_fecha_ultima_edicion_valoracion_reportada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='claridad_informacion',
            field=models.IntegerField(blank=True, help_text='Claridad de la información', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='coincidencia_fotos',
            field=models.IntegerField(blank=True, help_text='Coincidencia fotos/realidad', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='ubicacion_correcta',
            field=models.IntegerField(blank=True, help_text='Ubicación correcta', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
