# Generated by Django 4.2.27 on 2025-12-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0008_alter_valoracion_claridad_informacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='motivo_suspension',
            field=models.CharField(blank=True, help_text='Motivo por el cual la propiedad fue suspendida', max_length=255),
        ),
    ]
