# Generated by Django 4.2.27 on 2025-12-31 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0009_propiedad_motivo_suspension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('premium', 'Premium'), ('normal', 'Normal')], default='normal', max_length=20)),
                ('duracion_dias', models.IntegerField(choices=[(7, '7 días'), (15, '15 días'), (30, '30 días')])),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destacados', to='propiedades.propiedad')),
            ],
            options={
                'verbose_name': 'Destacado',
                'verbose_name_plural': 'Destacados',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['activo', 'fecha_fin'], name='propiedades_activo_dbf8c4_idx'), models.Index(fields=['tipo', 'fecha_inicio'], name='propiedades_tipo_e9d080_idx')],
            },
        ),
    ]
