# Generated by Django 4.2.27 on 2026-01-01 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0010_destacado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(help_text='El título debe tener entre 60 y 70 caracteres', max_length=200, validators=[django.core.validators.MinLengthValidator(60), django.core.validators.MaxLengthValidator(70)]),
        ),
    ]
