# Generated by Django 4.2.27 on 2026-01-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0011_alter_propiedad_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
