# Generated by Django 4.2.27 on 2026-01-04 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0013_remove_destacado_quota_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='accesibilidad',
            field=models.BooleanField(default=False, help_text='Apto para movilidad reducida'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='aire_acondicionado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='amenities',
            field=models.BooleanField(default=False, help_text='Tiene amenities (pileta, gym, SUM)'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='ascensor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='balcon',
            field=models.BooleanField(default=False, help_text='Tiene balcón o terraza'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='calefaccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='parrilla',
            field=models.BooleanField(default=False, help_text='Tiene parrilla'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='patio',
            field=models.BooleanField(default=False, help_text='Tiene patio o jardín'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='piso',
            field=models.IntegerField(blank=True, help_text='Número de piso', null=True, validators=[django.core.validators.MinValueValidator(-5)]),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='seguridad',
            field=models.BooleanField(default=False, help_text='Tiene seguridad o portero'),
        ),
    ]
