# Generated by Django 4.2.27 on 2026-01-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0014_propiedad_accesibilidad_propiedad_aire_acondicionado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='provincia',
            field=models.CharField(default='Buenos Aires', max_length=100),
        ),
    ]
