# Generated by Django 4.2.27 on 2026-03-16 07:03

from django.db import migrations, models
import propiedades.models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0015_propiedad_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenpropiedad',
            name='imagen',
            field=models.ImageField(upload_to='propiedades/', validators=[propiedades.models.validar_imagen_propiedad]),
        ),
    ]
