# Generated by Django 4.2.27 on 2026-08-19 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
        ('propiedades', '0016_alter_imagenpropiedad_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='ubicaciones.provincia'),
        ),
    ]
