# Generated by Django 4.2.27 on 2026-08-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0018_propiedad_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='area_deportiva',
            field=models.BooleanField(default=False, help_text='Cuenta con área o cancha deportiva'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='gimnasio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='jacuzzi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='lavanderia',
            field=models.BooleanField(default=False, help_text='Tiene lavadero o lavandería'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='piscina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='quincho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='sauna',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='solarium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='terraza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
