# Generated by Django 4.2.27 on 2026-09-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0019_propiedad_area_deportiva_propiedad_gimnasio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='tipo',
            field=models.CharField(choices=[('departamento', 'Departamento'), ('casa', 'Casa'), ('cuarto', 'Cuarto'), ('local', 'Local Comercial'), ('terreno', 'Terreno'), ('oficina', 'Oficina'), ('galpon', 'Galpón')], max_length=20),
        ),
    ]
